services:
  docs:
    image: active_annotate_local_docs
    container_name: active_annotate_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./active_annotate:/app/active_annotate:z
    ports:
      - '9000:9000'
    command: /start-docs
