services:
  ml-backend:
    build: .
    container_name: active_annotate_local_ml_backend
    ports:
      - "9090:9090"
    volumes:
      - ./model_weights:/model_weights
    restart: unless-stopped
